### ISSUE TITLE
Inline evaluation results no longer display in 2.0.216

### ISSUE THREAD

**Issue by S4G4R** [BetterThanTomorrow/calva#1332]
Version: 1.61.0 (user setup)
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by PEZ** [comment]
Thanks for reporting! Are you using GitLense perhaps?

**Comment by S4G4R** [comment]
I am using GitLens, yes. But disabling it doesn't seem to fix the bug.

**Comment by PEZ** [comment]
Thanks for trying that. Very strange. Do you have some other extension that annotates behind the line endings?

I suspect it is a race condition between Calva and some other extension, but I'm really unsure about it, because I can have GitLense line blames on w/o conflict with inline results.

BTW, anyone reading this and experiencing this bug. Run with Calva v2.0.215 for now. In the Extension pane, click the cogwheel in the Calva entry:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/30010/136904349-b2727cc7-48b7-42f4-a535-daf31ddd4f5c.png">

**Comment by S4G4R** [comment]
I disabled all my other extensions except Calva, but it still didn't fix it. Here are the ones that I am actively using :
- Calva
- GitHub Pull Requests and Issues
- GitLens
- PostgreSQL
- Remote-WSL
- One Dark Pro Theme (Tried changing this too)

**Comment by PEZ** [comment]
Hmmm. Does it work with `v2.0.215`? (I want to rule out that this is a freak coincidence with me changing how inline display is done. 😄)

**Comment by S4G4R** [comment]
It works fine with `2.0.215`, it's what I've been using since I found this bug.

**Comment by PEZ** [comment]
Thanks for updating about that. Since I can't reproduce the error, I might ask you for help debugging this. Would you be up for that? It's pretty easy to setup the dev environment, and it is detailed on the wiki.

**Comment by S4G4R** [comment]
Sure, no problem. I will have a look at the wiki and see if I can setup the environment.

**Comment by S4G4R** [comment]
@PEZ I have the dev environment setup. Let me know if there is anything specific I can do.

**Comment by PEZ** [comment]
That's awesome! The change that messes it up for you lives in `src/providers/annotations.ts`, in the function `evaluated`. You should be able to confirm that changing the `after:` keys to `:before` makes things work again.

I am curious about the difference in the DOM when it works and when it doesn't. If you open the developers tools (available from both the command palette and the **Help** menu) and inspect around the end of the line where the results are (or are not) displayed, maybe you can find a clue.

That's all I can think up right now. It is a very strange error.

**Comment by S4G4R** [comment]
Changing `after:` to `before:` (I think thats what you meant instead of `:before`?), doesn't seem to do much. 
Here is the error and stack trace that I get in the debug console though when I try to evaluate `(+ 1 1)` :
```
rejected promise not handled within 1 second: TypeError: contentText.replaceAll is not a function
/home/sagar/.vscode-server/bin/ee8c7def80afc00dd6e593ef12f37756d8f504ea/out/bootstrap-fork.js:5
stack trace: TypeError: contentText.replaceAll is not a function
    at evaluated (/home/sagar/calva/src/providers/annotations.ts:57:42)
    at Object.decorateResults (/home/sagar/calva/src/providers/annotations.ts:126:22)
    at /home/sagar/calva/src/evaluate.ts:95:45
    at Generator.next (<anonymous>)
    at /home/sagar/calva/out/evaluate.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sagar/calva/out/evaluate.js:4:12)
    at /home/sagar/calva/src/evaluate.ts:79:65
    at /home/sagar/calva/src/results-output/results-doc.ts:297:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by PEZ** [comment]
Ah, so it was that _other_ change. 😄  

This is even more strange, though. Why wouldn't `String.replaceAll()` be there... Can you catch it in the debugger and play around with a bit? Is contextText even a string?

**Comment by S4G4R** [comment]
All seems fine :
```
console.log(contentText)
console.log(typeof contentText)
```
Gives me :
```
=> 2
string
```

**Comment by PEZ** [comment]
So it is a string... please also check if any of these work:

```typescript
contentText.replaceAll(' ', "\u00a0")
contentText.replace(/ /g, "\u00a0")
```

**Comment by PEZ** [comment]
Debug tips: Instead of `console.log` you can use LogPoints. Right-click in the gutter to add one. Something like `{cotentText} : {typeof contentText}` in this case. Just good to know, in case you didn't. Also, I often find placing a break point and using the debug console is nice in aREPL-ish way.

**Comment by S4G4R** [comment]
`contentText.replaceAll(' ', "\u00a0")`
This one throws the same error as before.
`contentText.replace(/ /g, "\u00a0")`
This one works!

**Comment by PEZ** [comment]
Wow, that's so strange! Why wouldn't `replaceAll` be there... This probably means that a few other Calva features do not work for you. ... Hmmm, actually we only use `replaceAll` in one other feature: Custom command snippets.

I wonder if babel can be configured to fix it for us... But I also wonder about the root cause. ... Ah, a comment on this SO answer says it was added in nodejs 15. https://stackoverflow.com/a/1145525/44639 Which VS Code version are you on?

**Comment by PEZ** [comment]
`1.61.0`, it's the `Version` in the OP start, right? I wonder what **(user setup)** means...

**Comment by PEZ** [comment]
This is from the about box on my VS Code:

```
Version: 1.61.0
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:11:58.853Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

Putting yours here for easy comparison:

```
Version: 1.61.0 (user setup)
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by S4G4R** [comment]
It seems there are options for "User Installer" and "System Installer", and I may have chosen the former. Let me try the System Installer.
https://code.visualstudio.com/download

**Comment by S4G4R** [comment]
Well, all that has changed is instead of "user setup" it nows says "system setup" 😅. I think it is a Windows thing, and I noticed you are using Mac.
The bug also still persists.

**Comment by PEZ** [comment]
Now tested on my Windows machine and it works there.

```
Version: 1.61.0 (user setup)
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19041
```

This goes deeper. 😄 

We can of course use `replace` where we now use `replaceAll`. If you want to supply a PR, I'd be happy to accept. But we should then also create an issue about the root cause not being found. And we need to find it, because other bugs are lurking and/or waiting to happen.

**Comment by S4G4R** [comment]
I'd be happy to provide a PR. Should I create a separate issue to find the root cause?

**Comment by PEZ** [comment]
Awesome. Yes, please file an issue about `replaceAll` and link it here. Then in the PR you can put `Fixes #1332` and something like `Workaround for #<new issue>` That'll give us a good trail, I think.

Please also place the same workaround in `src/custom-snippets.ts`. 🙏

**Comment by S4G4R** [comment]
Linked : #1339
