### ISSUE TITLE
Peek definition not working

### ISSUE THREAD

**Issue by RiteekS** [BetterThanTomorrow/calva#49]
my peek definition is not working. what is the shortcut to use this peek definintion

**Comment by PEZ** [comment]
Hello, you should get docs if you hover over symbols and to peek you hold down the `command` key (on Mac, not sure what key it is on Windows and Linux).

However, there could be a dependency problem causing it to not work. Is this a Clojure or ClojureScript project? If the latter. is it Figwheel or Shadow CLJS?

**Comment by RiteekS** [comment]
this is a Clojure project @PEZ, I am getting `command 'calva.connect' not found` and i think this is the raeson not to work, i have all the pulgin what else I will have to do to make this work. please help 🙏

**Comment by apesic** [comment]
I'm getting the same error after upgrading to 1.24.1. Dev tools shows:

```
Activating extension 'cospaia.clojure4vscode' failed: Cannot find module 'immutable'.
```

**Comment by PEZ** [comment]
This is worrisome. What version of Calva are you guys using?

**Comment by apesic** [comment]
1.3.27 for me
